// scripts/seed-word-library.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  makeCurriculumEntry,
  makeWordCore,
  validateEntry,
} from '../src/data/words/builders';
import { graphemePool } from '../src/data/words/levels';
import type {
  CurriculumEntry,
  WordCore,
} from '../src/data/words/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, '..');
const sourceFile = path.join(
  repoRoot,
  'docs/superpowers/plans/2026-04-11-phonic-word-library_words-list.md',
);
const wordsDir = path.join(repoRoot, 'src/data/words');
const reviewFile = path.join(
  repoRoot,
  'docs/superpowers/plans/2026-04-11-phonics-word-library_codegen-review.md',
);

interface LevelBlock {
  level: number;
  words: string[];
}

const parseSource = (md: string): LevelBlock[] => {
  const blocks: LevelBlock[] = [];
  const levelRegex = /##\s+level\s+(\d+)/gi;
  const matches = [...md.matchAll(levelRegex)];
  for (let i = 0; i < matches.length; i++) {
    const match = matches[i]!;
    const level = Number(match[1]);
    const start = match.index + match[0].length;
    const end =
      i + 1 < matches.length ? matches[i + 1]!.index : md.length;
    const chunk = md.slice(start, end);
    const wordsLine = /\*\s+words:\s+\[([^\]]+)\]/i.exec(chunk);
    if (!wordsLine) continue;
    const words = wordsLine[1]!
      .split(',')
      .map((w) => w.trim())
      .filter(Boolean);
    blocks.push({ level, words });
  }
  return blocks;
};

const isProperNoun = (word: string): boolean => /^[A-Z]/.test(word);

interface SeedResult {
  coreByLevel: Map<number, WordCore[]>;
  curriculumByLevel: Map<number, CurriculumEntry[]>;
  review: string[];
}

const seed = (blocks: LevelBlock[]): SeedResult => {
  const coreByLevel = new Map<number, WordCore[]>();
  const curriculumByLevel = new Map<number, CurriculumEntry[]>();
  const review: string[] = [];
  const seen = new Map<string, number>(); // word → level first assigned

  for (const block of blocks) {
    const pool = graphemePool(block.level);
    for (const rawWord of block.words) {
      if (isProperNoun(rawWord)) continue;
      const word = rawWord.toLowerCase();
      if (seen.has(word)) continue; // dedup: first level wins
      seen.set(word, block.level);

      const core = makeWordCore(word);
      if (!coreByLevel.has(block.level))
        coreByLevel.set(block.level, []);
      coreByLevel.get(block.level)!.push(core);

      const entry = makeCurriculumEntry(word, block.level, {
        levelGraphemes: pool,
      });

      if (entry === null) {
        review.push(
          `- \`${word}\` (level ${block.level}) — could not derive graphemes from set [${pool.join(', ')}]`,
        );
        continue;
      }

      const v = validateEntry(core, entry);
      if (!v.ok) {
        review.push(
          `- \`${word}\` (level ${block.level}) — ${v.errors.map((e) => e.message).join('; ')}`,
        );
        continue;
      }

      if (!curriculumByLevel.has(block.level))
        curriculumByLevel.set(block.level, []);
      curriculumByLevel.get(block.level)!.push(entry);
    }
  }

  // Deterministic output: alphabetical by word, locale-pinned to match writer.ts.
  for (const arr of coreByLevel.values())
    arr.sort((a, b) => a.word.localeCompare(b.word, 'en'));
  for (const arr of curriculumByLevel.values())
    arr.sort((a, b) => a.word.localeCompare(b.word, 'en'));

  return { coreByLevel, curriculumByLevel, review };
};

const writeJson = (filePath: string, data: unknown): void => {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
};

const writeStub = (region: string): void => {
  const stubPath = path.join(
    wordsDir,
    'curriculum',
    region,
    '.gitkeep',
  );
  mkdirSync(path.dirname(stubPath), { recursive: true });
  writeFileSync(stubPath, '', 'utf8');
};

const main = (): void => {
  const md = readFileSync(sourceFile, 'utf8');
  const blocks = parseSource(md);
  const { coreByLevel, curriculumByLevel, review } = seed(blocks);

  for (const [level, entries] of coreByLevel.entries()) {
    writeJson(
      path.join(wordsDir, 'core', `level${level}.json`),
      entries,
    );
  }
  for (const [level, entries] of curriculumByLevel.entries()) {
    writeJson(
      path.join(wordsDir, 'curriculum', 'aus', `level${level}.json`),
      entries,
    );
  }

  for (const region of ['uk', 'us', 'br']) writeStub(region);

  const reviewMd = [
    '# Phonics Library Codegen Review',
    '',
    '> Auto-generated by `scripts/seed-word-library.ts`. This lists words',
    '> that could not be auto-enriched with Tier 2 data (IPA + graphemes)',
    '> during seeding. Each entry needs hand-review, typically via P2',
    '> (the dev authoring form) once it lands.',
    '',
    `Total flagged: **${review.length}**`,
    '',
    ...review,
    '',
  ].join('\n');
  writeFileSync(reviewFile, reviewMd, 'utf8');

  const coreTotal = [...coreByLevel.values()].reduce(
    (n, arr) => n + arr.length,
    0,
  );
  const curriculumTotal = [...curriculumByLevel.values()].reduce(
    (n, arr) => n + arr.length,
    0,
  );
  console.log(
    `Seeded ${coreTotal} core words; ${curriculumTotal} enriched AUS curriculum entries; ${review.length} flagged for review.`,
  );
};

main();
