/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppParentRouteImport } from './routes/_app/parent'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppParentIndexRouteImport } from './routes/_app/parent/index'
import { Route as AppParentVoicesRouteImport } from './routes/_app/parent/voices'
import { Route as AppParentSyncRouteImport } from './routes/_app/parent/sync'
import { Route as AppParentOverridesRouteImport } from './routes/_app/parent/overrides'
import { Route as AppParentHistoryRouteImport } from './routes/_app/parent/history'
import { Route as AppParentDataRouteImport } from './routes/_app/parent/data'
import { Route as AppGameGameIdRouteImport } from './routes/_app/game/$gameId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentVoicesRoute = AppParentVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentSyncRoute = AppParentSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentOverridesRoute = AppParentOverridesRouteImport.update({
  id: '/overrides',
  path: '/overrides',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentHistoryRoute = AppParentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppParentRoute,
} as any)
const AppParentDataRoute = AppParentDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppParentRoute,
} as any)
const AppGameGameIdRoute = AppGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/parent': typeof AppParentRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/game/$gameId': typeof AppGameGameIdRoute
  '/parent/data': typeof AppParentDataRoute
  '/parent/history': typeof AppParentHistoryRoute
  '/parent/overrides': typeof AppParentOverridesRoute
  '/parent/sync': typeof AppParentSyncRoute
  '/parent/voices': typeof AppParentVoicesRoute
  '/parent/': typeof AppParentIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/game/$gameId': typeof AppGameGameIdRoute
  '/parent/data': typeof AppParentDataRoute
  '/parent/history': typeof AppParentHistoryRoute
  '/parent/overrides': typeof AppParentOverridesRoute
  '/parent/sync': typeof AppParentSyncRoute
  '/parent/voices': typeof AppParentVoicesRoute
  '/parent': typeof AppParentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/parent': typeof AppParentRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/game/$gameId': typeof AppGameGameIdRoute
  '/_app/parent/data': typeof AppParentDataRoute
  '/_app/parent/history': typeof AppParentHistoryRoute
  '/_app/parent/overrides': typeof AppParentOverridesRoute
  '/_app/parent/sync': typeof AppParentSyncRoute
  '/_app/parent/voices': typeof AppParentVoicesRoute
  '/_app/parent/': typeof AppParentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/parent'
    | '/settings'
    | '/game/$gameId'
    | '/parent/data'
    | '/parent/history'
    | '/parent/overrides'
    | '/parent/sync'
    | '/parent/voices'
    | '/parent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/settings'
    | '/'
    | '/game/$gameId'
    | '/parent/data'
    | '/parent/history'
    | '/parent/overrides'
    | '/parent/sync'
    | '/parent/voices'
    | '/parent'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/parent'
    | '/_app/settings'
    | '/_app/'
    | '/_app/game/$gameId'
    | '/_app/parent/data'
    | '/_app/parent/history'
    | '/_app/parent/overrides'
    | '/_app/parent/sync'
    | '/_app/parent/voices'
    | '/_app/parent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent': {
      id: '/_app/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/': {
      id: '/_app/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/voices': {
      id: '/_app/parent/voices'
      path: '/voices'
      fullPath: '/parent/voices'
      preLoaderRoute: typeof AppParentVoicesRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/sync': {
      id: '/_app/parent/sync'
      path: '/sync'
      fullPath: '/parent/sync'
      preLoaderRoute: typeof AppParentSyncRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/overrides': {
      id: '/_app/parent/overrides'
      path: '/overrides'
      fullPath: '/parent/overrides'
      preLoaderRoute: typeof AppParentOverridesRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/history': {
      id: '/_app/parent/history'
      path: '/history'
      fullPath: '/parent/history'
      preLoaderRoute: typeof AppParentHistoryRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/parent/data': {
      id: '/_app/parent/data'
      path: '/data'
      fullPath: '/parent/data'
      preLoaderRoute: typeof AppParentDataRouteImport
      parentRoute: typeof AppParentRoute
    }
    '/_app/game/$gameId': {
      id: '/_app/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AppGameGameIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppParentRouteChildren {
  AppParentDataRoute: typeof AppParentDataRoute
  AppParentHistoryRoute: typeof AppParentHistoryRoute
  AppParentOverridesRoute: typeof AppParentOverridesRoute
  AppParentSyncRoute: typeof AppParentSyncRoute
  AppParentVoicesRoute: typeof AppParentVoicesRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
}

const AppParentRouteChildren: AppParentRouteChildren = {
  AppParentDataRoute: AppParentDataRoute,
  AppParentHistoryRoute: AppParentHistoryRoute,
  AppParentOverridesRoute: AppParentOverridesRoute,
  AppParentSyncRoute: AppParentSyncRoute,
  AppParentVoicesRoute: AppParentVoicesRoute,
  AppParentIndexRoute: AppParentIndexRoute,
}

const AppParentRouteWithChildren = AppParentRoute._addFileChildren(
  AppParentRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppParentRoute: typeof AppParentRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGameGameIdRoute: typeof AppGameGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppParentRoute: AppParentRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGameGameIdRoute: AppGameGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
